django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from toys import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('login/', CustomLoginView.as_view(), name='login'),
    path('profile/', views.profile, name='profile'),
    path('confirm/', views.confirm, name='confirm'),
    path('email-list-signup/', views.new, name='email-list-signup'),

    path('delete/', views.delete, name='delete'),
    path('register/', views.register, name='register'),
    path('password_change/', views.password_change, name='password_change'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password_reset.html'
         ),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'
         ),
         name='password_reset_complete'),

    path('', include('toys.urls', namespace='toys'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/toys/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (
    ItemDetailView,
    CheckoutView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart, RulesView, AboutView, ContactsView, CustomLoginView,
)

app_name = "toys"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path("contact", views.contact, name="contact"),
    path('email-list-signup/', views.new, name='email-list-signup'),
    path('confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
    path('about/', AboutView.as_view(), name='about'),
    path('rules/', RulesView.as_view(), name='rules'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),

]

django_project/toys/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm
from django.db.models.signals import post_save
from django.dispatch import receiver

from .models import Customer


class UserRegisterForm(UserCreationForm):
    error_messages = {
        'password_mismatch': 'Два введенных пароля не совпадают'
    }
    email = forms.EmailField(error_messages={'invalid': 'Введите корректный email-адрес'})
    password1 = forms.CharField(label='Пароль',
                                widget=(forms.PasswordInput(attrs={'class': 'form-control'})),
                                )
    password2 = forms.CharField(label='Подтверждение пароля',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                )
    username = forms.CharField(
        label="Имя пользователя",
        max_length=150,
        error_messages={'unique': "Пользователь с таким именем уже существует"},
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError(
                "Пользователь с таким email-адресом уже существует")
        return super(UserRegisterForm, self).clean(*args, **kwargs)

    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwargs):
        if created:
            Customer.objects.create(user=instance)


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    phone = forms.CharField()

    class Meta:
        model = Customer
        fields = ['username', 'email', 'phone']


class CustomAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        label='Имя',
        widget=forms.TextInput(attrs={'autofocus': True})
    )
    password = forms.CharField(
        label="Пароль",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )


class CustomPassChangeForm(PasswordChangeForm):
    new_password1 = forms.CharField(
        label="Пароль",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'})
    )


class ContactForm(forms.Form):
    name = forms.CharField(max_length = 50)
    from_email = forms.EmailField(max_length = 150)
    message = forms.CharField(widget = forms.Textarea, max_length = 2000)
    subject = forms.CharField(max_length = 100)


class SubscriberForm(forms.Form):
    email = forms.EmailField(label='Your email',
                             max_length=100,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

django_project/toys/views.py
import random
import ssl

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core import mail
from django.core.mail import send_mail, EmailMessage, mail_admins, BadHeaderError
from django.core.validators import EmailValidator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.views import LoginView

from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.template.loader import get_template, render_to_string
from django.utils import timezone
from django.utils.html import strip_tags
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.csrf import csrf_exempt
from sendgrid import Mail, SendGridAPIClient

from .forms import UserRegisterForm, CustomAuthenticationForm, UserUpdateForm, CustomPassChangeForm, ContactForm, \
    SubscriberForm

from django.contrib.auth.models import User

from .mixins import CartMixin
from .models import Item, OrderItem, Order, Customer, Subscriber
from django.views.generic import (
    View,
    ListView,
    DetailView,
)
from django import forms

ssl._create_default_https_context = ssl._create_unverified_context


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm


class ItemDetailView(CartMixin, DetailView):
    model = Item

    def get(self, request, slug, *args, **kwargs):
        item = Item.objects.get(slug=slug)
        context = {
            'object': item,
            'order': self.order
        }
        return render(request, 'product.html', context)


def home(request, *args, **kwargs):
    # paginate_by = 10
    # template_name = "home.html"
    try:
        customer = request.user.customer
        print("1")

    except:
        print("2")

        try:
            device = request.COOKIES['device']
            print("3")

            customer, created = Customer.objects.get_or_create(device=device)
            print("4")

        except:
            print("5")

            context = {
                'products': Item.objects.all(),
            }

            return render(request, 'home.html', context)

    qs = Order.objects.filter(customer=customer, ordered=False)
    if qs.exists():
        order = qs[0]
    else:
        order = False
    context = {
        'products': Item.objects.all(),
        'order': order,
        'form': SubscriberForm
    }
    return render(request, 'home.html', context)


class AboutView(CartMixin, ListView):
    model = Item
    template_name = "about.html"

    def get(self, request, *args, **kwargs):
        context = {'order': self.order}
        return render(request, 'about.html', context)


class ContactsView(CartMixin, ListView):
    model = Item
    template_name = "contacts.html"

    def get(self, request, *args, **kwargs):
        context = {'order': self.order}
        return render(request, 'contacts.html', context)


class RulesView(CartMixin, ListView):
    model = Item
    template_name = "rules.html"

    def get(self, request, *args, **kwargs):
        context = {'order': self.order}
        return render(request, 'rules.html', context)


def add_to_cart(request, slug):
    try:
        customer = request.user.customer
    except:
        try:
            device = request.COOKIES['device']
            customer, created = Customer.objects.get_or_create(device=device)
        except:
            return render(request, '403_csrf.html')

    # customer, created = Customer.objects.get_or_create(user=request.user)
    customer.save()
    item = get_object_or_404(Item, slug=slug)

    order_qs = Order.objects.filter(customer=customer, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        order_item, created = OrderItem.objects.get_or_create(item=item, order=order, ordered=False)

        if created:
            order_item.quantity = 1
            order_item.save()
            order.save()
            messages.info(request, "This item quantity was updated.")
            return redirect("toys:order-summary")
        else:
            order_item.quantity += 1
            order_item.save()
            order.save()
            messages.info(request, "This item was added to your cart.")
            return redirect("toys:order-summary")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(customer=customer, ordered_date=ordered_date)
        order_item, created = OrderItem.objects.get_or_create(
            item=item,
            order=order,
            ordered=False
        )
        order_item.quantity = 1
        order_item.save()
        order.save()
        messages.info(request, "This item was added to your cart.")
        return redirect("toys:order-summary")


def remove_from_cart(request, slug):
    try:
        customer = request.user.customer
    except:
        try:
            device = request.COOKIES['device']
            customer, created = Customer.objects.get_or_create(device=device)
        except:
            return render(request, '403_csrf.html')

    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(customer=customer, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        orderitems = order.orderitem_set.all()

        if orderitems.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                order=order,
                ordered=False
            )[0]
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("toys:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("toys:product", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("toys:product", slug=slug)


def remove_single_item_from_cart(request, slug):
    try:
        customer = request.user.customer
    except:
        try:
            device = request.COOKIES['device']
            customer, created = Customer.objects.get_or_create(device=device)
        except:
            return render(request, '403_csrf.html')

    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        customer=customer,
        ordered=False
    )

    if order_qs.exists():
        order = order_qs[0]
        orderitems = order.orderitem_set.all()

        if orderitems.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                order=order,
                ordered=False
            )[0]

            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order_item.delete()

            messages.info(request, "This item quantity was updated.")
            return redirect("toys:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("toys:product", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("toys:product", slug=slug)


class OrderSummaryView(CartMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            try:
                customer = request.user.customer
            except:
                try:
                    device = request.COOKIES['device']
                    customer, created = Customer.objects.get_or_create(device=device)
                except:
                    return render(request, '403_csrf.html')

            order = Order.objects.get(customer=customer, ordered=False)

            context = {'object': order,
                       'order': self.order
                       }
            return render(self.request, 'order_summary.html', context)

            context = {'order': self.order}
            return render(request, 'about.html', context)

        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")


class CheckoutForm(forms.Form):
    phone = forms.CharField(required=False)
    email = forms.EmailField(required=True)
    username = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['phone', 'email', 'username']


def is_email(value):
    try:
        EmailValidator()(value)
    except ValidationError:
        return False
    else:
        return True


# def sendmail(customer, order):
#     eemail = customer.email
#     ctx = {
#         'user': customer.username,
#         'order': order
#     }
#     message = get_template('email.html').render(ctx)
#     msg = EmailMessage(
#         'Subject',
#         message,
#         'vp7007@gmail.com',
#         [eemail],
#     )
#     msg.content_subtype = "html"  # Main content is now text/html
#     msg.send()




def sendmail1(customer, order):
    # Order confirmation to customer email
    subject = 'Order confirmation'
    eemail = customer.email
    html_message = render_to_string('email.html', {'user': customer.username,
                                                   'order': order,
                                                   'phone': customer.phone,
                                                   'email': eemail})
    plain_message = strip_tags(html_message)
    from_email = 'From <vp7007@gmail.com>'
    to = eemail

    mail.send_mail(subject, plain_message, from_email, [to], fail_silently=False, html_message=html_message)



def sendmail_admin(customer, order):
    # New order notification to admins
    subject = 'New order notification'
    eemail = customer.email
    html_message = render_to_string('email_admins.html', {'user': customer.username,

django_project/toys/templates/403_csrf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h3 style ="color: #0E92FA"> Для корректной работы сайта (в частности, для регистрации или оформления заказа)
    в вашем браузере должны быть включены cookie файлы.
</h3>
</body>
</html>

django_project/toys/templates/contact.html
<!--Contact form-->
	<div style="margin:80px">
		<h1>Contact</h1>
		<h4>Contact us directly if you have any questions</h4>
		<p>
			Please write your name, email address and a message below if you have any questions.
			One of our staff members will be happy to contact you directly and answer your questions as soon as possible.
		</p>
		<form method="post">
        {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Submit</button>
        </form>
    </div>

django_project/toys/templates/email_admins.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-color:#c0edfe; margin-top: -17px;">
Поступил новый заказ.
Покупатель - {{ user }}
Телефон - {{phone}}
email - {{email}}
          {% include "order_snippet.html" %}

</body>
</html>

django_project/toys/templates/home.html
{% extends "base.html" %}
{% block content %}
<body style="background-color:#c0edfe; margin-top: 130px;">
<div class="container-fluid ml-1 mr-1 pl-1 pr-1">
            {%  for item in products  %}
                {% if forloop.counter0|divisibleby:4 %} <div class="row text-center"> {%  endif %}
                  <div class="col-md-3 p-0 m-0">
                <a href="{{ item.get_absolute_url }}">
                      <div class="card ">
                            <div class="border border-3 rounded" style="border-width:1px !important; border-color: #c0edfe !important;">
                              <img class="card-img-top img-fluid "  src="{{  item.image1.url }}"  alt="None">
                                <div class="card-content" style="background-color: #feffcc">
                                     <h5 class="card-title mb-0 " style="color: #blue">{{ item.name }}</h5>
                                    <p class="card-text" style="color: #FD4A85; font-weight: bold">{{ item.price }} руб</p>
                                </div><!-- card content -->
                          </div>
                      </div><!-- card -->
                      </a>
                  </div><!-- col-md-5 -->

            {%  if forloop.counter|divisibleby:4 or forloop.last %}
                </div><!-- row closing -->{%  endif %}
            {%  endfor %}
         </div><!-- container -->
</body>

<div class="container mt-5">
            <div class="col-12">
                <h1>Email Newsletter</h1>
            </div>
            <div class="col-12">
                {% if email %}
                <p>{{ email }} has been {{ action }}.</p>
                {% endif %}
            </div>
        {% if form %}
            <div class="col-12 col-md-4">
                <form action="{% url 'email-list-signup' %}" method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <br>
                    <button type="submit" class="btn btn-success">Subscribe!</button>
                </form>
            </div>
        {% endif %}
        </div>
<div class="mt-3 text-center">


            <a href="{% url 'toys:contact' %}">Связаться с нами</a>
</div>
<div class="footer-copyright py-3 mt-3 text-center" >
    <a href="https://vk.com/vladimir.leon" target="_blank">
<b>Вконтакте</b> <i class="fab fa-vk"> </i>

    </a>
    <br>
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
{% endblock content %}

django_project/toys/templates/logout.html
{% extends "base.html" %}
{% block content %}
<div style="margin-top: 150px; margin-left: 100px">
    <h2>Вы успешно вышли из аккаунта</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'toys:login' %}">Войти снова</a>
        </small>
    </div>
    </div>
{% endblock content %}

django_project/toys/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<head>
<script src='https://kit.fontawesome.com/a076d05399.js'></script>

</head>
  <main style="background-color:#c0edfe; margin-top: 0;">
    <div class="container mt-n2">

    <div class="table-responsive text-nowrap">
    <h2>Корзина</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Наименование</th>
            <th scope="col">Цена, руб</th>
            <th scope="col">Количество</th>
            <th scope="col">Общая стоимость</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object.orderitem_set.all %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ item.item.name}}</td>


            <td>{{ item.item.price }}</td>
            <td>
                <a href="{% url 'toys:remove-single-item-from-cart' item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ item.quantity }}
                <a href="{% url 'toys:add-to-cart' item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if item.item.discount_price %}
                {{ item.get_total_discount_item_price }} руб
                <span class="badge badge-primary">Экономия ${{ item.get_amount_saved }}</span>
            {% else %}
                {{ item.get_total_item_price }} руб
            {% endif %}
            <a style='color: red;' href="{% url 'toys:remove-from-cart' item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'><h5>Ваша корзина пуста</h5></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Продолжить покупки</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.get_total %}
            <tr style="background-color:#DDF6FF;">
            <td colspan="4"> <b>Итого</b></td>
            <td><b>{{ object.get_total }} руб</b></td>
            </tr>
            <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Оформить заказ</a>
            <a class='btn btn-primary float-right' href='/'>Продолжить покупки</a>
            </td>
            </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

django_project/toys/templates/password_change.html
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>

django_project/toys/templates/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
    <div class="alert alert-info">
        Ваш пароль был успешно изменен.
    </div>
    <a href="{% url 'toys:login' %}">Войти снова</a>
{% endblock content %}

django_project/toys/templates/password_reset_done.html
{% extends "base.html" %}
{% block content %}
    <div class="alert alert-info" style="background-color:#c0edfe; margin-top: 130px;">
        An email has been sent with instructions to reset your password
    </div>
{% endblock content %}

django_project/toys/templates/product.html
{% extends "base.html" %}
{% block content %}

<body style="background-color:#c0edfe; margin-top: 130px;">
    <div class="container-fluid ml-0 mr-1 pl-0 pr-0 ">
          <div class="row no-gutters ">
                <div class="col-md-6 pl-0 ">
                    <div id="carouselExampleFade" class="carousel slide" data-pause="false" data-interval="4000" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                            <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
                            <li data-target="#carouselExampleCaptions" data-slide-to="4"></li>
                        </ol>
                        <div class="carousel-inner ">
                            <div class="carousel-item active">
                                    <a href="{{ object.image1.url }}"  target="_blank">
                                        <img class="d-block w-100 " src="{{ object.image1.url }}" alt="First slide">
                                    </a>
                            </div>
                            <div class="carousel-item">
                                <a href="{{ object.image2.url }}"  target="_blank">
                                  <img class="d-block w-100" src="{{ object.image2.url }}" alt="Second slide">
                                </a>
                            </div>
                            <div class="carousel-item">
                                <a href="{{ object.image3.url }}"  target="_blank">
                                  <img class="d-block w-100" src="{{ object.image3.url }}" alt="Third slide">
                                </a>
                            </div>
                              <div class="carousel-item">
                                  <a href="{{ object.image4.url }}"  target="_blank">
                                    <img class="d-block w-100" src="{{ object.image4.url }}" alt="Third slide">
                                  </a>
                               </div>
                                <div class="carousel-item">
                                    <a href="{{ object.image5.url }}"  target="_blank">
                                        <img class="d-block w-100" src="{{ object.image5.url }}" alt="Third slide">
                                    </a>
                                </div>
                        </div>
                              <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                            </a>
                             <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                            </a>
                    </div>
                </div>
                        <div class="col-md-6 pl-4 pt-3 pr-3">
                            <div class="border border-3 rounded" style="border-width:6px !important; border-color: #ffd6f5 !important;">
                                <div class="p-3"  style="background-color:white;">
                                <h2 style="color: #7db3e8; font-weight: bold;" >{{ object.name }}</h2>
                                <p style="text-align: justify;">{{ object.description | linebreaks }}</p>
<!--                             <h4 style="color: #ff99e6; font-weight: bold; text-align: right; margin-right: 17px">{{ object.price }} руб</h4>-->
                                <h4 style="color: #FD4A85; font-weight: bold; text-align: right; margin-right: 17px">
                                {% if object.discount_price %}
                                    <span class="mr-1">
                                        <del>{{ object.price }} руб</del>
                                    </span>
                                    <span>{{ object.discount_price }} руб</span>
                                    {% else %}
                                        <span>{{ object.price }} руб</span>
                                    {% endif %}
                                </h4>
                                    {% comment %} <form class="d-flex justify-content-left">
                                          <!-- Default input -->
                                          <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
                                          <button class="btn btn-primary btn-md my-0 p" type="submit">
                                            Add to cart
                                            <i class="fas fa-shopping-cart ml-1"></i>
                                          </button>

                                            </form> {% endcomment %}
                                            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                                              Добавить в корзину
                                          <i class="fas fa-shopping-cart ml-1"></i>
                                         </a>
                                         <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                                           Удалить из корзины
                                         </a>
</div>
                            </div>
                        </div>
          </div>
    </div>
</body>
{% endblock content %}

django_project/toys/templates/products.html
{% extends "base.html" %}
{% block content %}
<body style="background-color:#FFF8DC; margin-top: 130px;">
<div class="container-fluid ml-1 mr-1 pl-1 pr-1">
            {%  for product in products  %}
                {% if forloop.counter0|divisibleby:4 %} <div class="row text-center"> {%  endif %}
                  <div class="col-md-3 p-0 m-0">
                      <a href="{% url 'product-detail' product.id %}">
                      <div class="card">
                          <div class="card border-warning">
                              <img class="card-img-top img-fluid "  src="{{ product.image1.url }}"  alt="None">
                                <div class="card-content">
                                     <h5 class="card-title mb-0 " style="color: #0E92FA">{{ product.name }}</h5>
                                    <p class="card-text" style="color: #FF6262; font-weight: bold">{{ product.price }} руб</p>
                                </div><!-- card content -->
                          </div>
                      </div><!-- card -->
                      </a>
                  </div><!-- col-md-5 -->

            {%  if forloop.counter|divisibleby:4 or forloop.last %}</div><!-- row closing -->{%  endif %}
            {%  endfor %}
         </div><!-- container -->
</body>
{% endblock content %}

django_project/toys/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section" style="background-color:#c0edfe; margin-top: 130px;">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group" style="margin-left: 100px; margin-right: 700px">
                <legend class="border-bottom mb-4"><h2>Регистрация</h2></legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group" style="margin-left: 100px">
                <button class="btn btn-outline-info" type="submit">Зарегистрироваться</button>
            </div>
        </form>
        <div class="border-top pt-3" style="margin-left: 100px">
            <small class="text-muted">
                Уже есть аккаунт? <a class="ml-2" href="{% url 'toys:login' %}">Войти</a>
            </small>
        </div>
    </div>
{% endblock content %}